export const lightTheme = {
  background: '#ffffff',
  foreground: '#1a1a1a',
  card: '#ffffff',
  cardForeground: '#1a1a1a',
  popover: '#ffffff',
  popoverForeground: '#1a1a1a',
  primary: '#2c5282',
  primaryForeground: '#ffffff',
  secondary: '#4a5568',
  secondaryForeground: '#ffffff',
  muted: '#f7fafc',
  mutedForeground: '#718096',
  accent: '#edf2f7',
  accentForeground: '#1a1a1a',
  destructive: '#c53030',
  destructiveForeground: '#ffffff',
  border: '#e2e8f0',
  input: '#f7fafc',
  ring: '#2c5282',
  radius: 4, // Slightly reduced radius for a more classic look
};

export const darkTheme = {
  background: '#1a202c',
  foreground: '#f7fafc',
  card: '#2d3748',
  cardForeground: '#f7fafc',
  popover: '#2d3748',
  popoverForeground: '#f7fafc',
  primary: '#4299e1',
  primaryForeground: '#ffffff',
  secondary: '#718096',
  secondaryForeground: '#ffffff',
  muted: '#2d3748',
  mutedForeground: '#a0aec0',
  accent: '#2d3748',
  accentForeground: '#f7fafc',
  destructive: '#e53e3e',
  destructiveForeground: '#ffffff',
  border: '#2d3748',
  input: '#2d3748',
  ring: '#4299e1',
  radius: 4,
};
