export const lightTheme = {
  background: '#f8f8f8',
  foreground: '#0c1b3b',
  card: '#ffffff',
  cardForeground: '#0c1b3b',
  popover: '#ffffff',
  popoverForeground: '#0c1b3b',
  primary: '#e63e3e',
  primaryForeground: '#ffffff',
  secondary: '#1c4a8c',
  secondaryForeground: '#ffffff',
  muted: '#f1f5f9',
  mutedForeground: '#64748b',
  accent: '#e2e8f0',
  accentForeground: '#0c1b3b',
  destructive: '#dc2626',
  destructiveForeground: '#ffffff',
  border: '#e2e8f0',
  input: '#f1f5f9',
  ring: '#e63e3e',
  radius: 6, // equivalent to 0.375rem
};

export const darkTheme = {
  background: '#1a2234',
  foreground: '#ffffff',
  card: '#1e293b',
  cardForeground: '#ffffff',
  popover: '#1e293b',
  popoverForeground: '#ffffff',
  primary: '#e63e3e',
  primaryForeground: '#ffffff',
  secondary: '#3b82f6',
  secondaryForeground: '#ffffff',
  muted: '#1e293b',
  mutedForeground: '#94a3b8',
  accent: '#262f42',
  accentForeground: '#ffffff',
  destructive: '#b91c1c',
  destructiveForeground: '#ffffff',
  border: '#262f42',
  input: '#1e293b',
  ring: '#e63e3e',
  radius: 6,
};
